
services:
  wyoming-rapidfuzz-proxy:
    container_name: wyoming-rapidfuzz-proxy
    image: wyoming-rapidfuzz-proxy:latest
    environment:
      - URI=tcp://0.0.0.0:10310
      - STT_URI=tcp://HOME_ASSISTANT_IP_OR_URI:10300
      - CORRECTION_THRESHOLD=15
      - LANGUAGE=es
      - DEBUG_LOGGING=TRUE
      - LIMIT_SENTENCES=TRUE
      - ALLOW_UNKNOWN=FALSE
      - HASS_TOKEN=LONG_LIVED_TOKEN_HERE
      - HASS_URI=ws://HOME_ASSISTANT_IP_OR_URI:8123/api/websocket
    volumes:
      - ./data:/data
    ports:
      - 10310:10310
    restart: unless-stopped
        
